# Develop override settings

url: "https://mayankb11.github.io/"

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mayankb11-github-io.disqus.com"

sass:
  style: expanded